export const ADMIN_PERMISSIONS_MAP: Record<string, string> = {
  MIX: 'MODULE_MIX',
  VALIDADOS: 'MODULE_VALIDADOS',
  NOVO_PEDIDO: 'MODULE_NOVO_PEDIDO',
  DESPESA: 'MODULE_DESPESA',
  COTA: 'MODULE_COTA'
};