
import { Role } from './roles';

export type PermissionKey = 
  | 'MODULE_DASHBOARD_ADMIN'
  | 'MODULE_DASHBOARD_MANAGER'
  | 'MODULE_METAS'
  | 'MODULE_PURCHASES'
  | 'MODULE_COTAS'
  | 'MODULE_ICECREAM'
  | 'MODULE_GELATERIA_PDV'
  | 'MODULE_GELATERIA_ESTOQUE'
  | 'MODULE_GELATERIA_DRE_DIARIO'
  | 'MODULE_GELATERIA_DRE_MENSAL'
  | 'MODULE_GELATERIA_AUDIT'
  | 'MODULE_GELATERIA_CONFIG'
  | 'MODULE_CASH_REGISTER'
  | 'MODULE_FINANCIAL'
  | 'MODULE_CASH_ERRORS'
  | 'MODULE_AGENDA'
  | 'MODULE_MARKETING'
  | 'MODULE_DOWNLOADS'
  | 'MODULE_DOCUMENTS'
  | 'MODULE_ADMIN_USERS'
  | 'MODULE_ACCESS_CONTROL'
  | 'MODULE_AUDIT'
  | 'MODULE_SETTINGS';

export const PERMISSIONS_MAP: Record<PermissionKey, Role[]> = {
  MODULE_DASHBOARD_ADMIN: ['ADMIN'],
  MODULE_DASHBOARD_MANAGER: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_METAS: ['ADMIN'],
  MODULE_PURCHASES: ['ADMIN', 'MANAGER', 'CASHIER', 'ICE_CREAM'],
  MODULE_COTAS: ['ADMIN', 'MANAGER', 'CASHIER', 'ICE_CREAM'],
  MODULE_ICECREAM: ['ADMIN', 'MANAGER', 'CASHIER', 'ICE_CREAM'],
  MODULE_GELATERIA_PDV: ['ADMIN', 'MANAGER', 'CASHIER', 'ICE_CREAM'],
  MODULE_GELATERIA_ESTOQUE: ['ADMIN', 'MANAGER', 'CASHIER', 'ICE_CREAM'],
  MODULE_GELATERIA_DRE_DIARIO: ['ADMIN', 'MANAGER', 'CASHIER', 'ICE_CREAM'],
  MODULE_GELATERIA_DRE_MENSAL: ['ADMIN', 'MANAGER', 'ICE_CREAM'],
  MODULE_GELATERIA_AUDIT: ['ADMIN', 'MANAGER', 'ICE_CREAM'],
  MODULE_GELATERIA_CONFIG: ['ADMIN', 'MANAGER', 'ICE_CREAM'],
  MODULE_CASH_REGISTER: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_FINANCIAL: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_CASH_ERRORS: ['ADMIN', 'CASHIER', 'MANAGER'],
  MODULE_AGENDA: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_MARKETING: ['ADMIN', 'MANAGER'],
  MODULE_DOWNLOADS: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_DOCUMENTS: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_ADMIN_USERS: ['ADMIN'],
  MODULE_ACCESS_CONTROL: ['ADMIN'],
  MODULE_AUDIT: ['ADMIN'],
  MODULE_SETTINGS: ['ADMIN']
};
