
import { Role } from './roles';

export type PermissionKey = 
  | 'MODULE_DASHBOARD'
  | 'MODULE_METAS'
  | 'MODULE_PURCHASES'
  | 'MODULE_COTAS'
  | 'MODULE_ICECREAM'
  | 'MODULE_CASH_REGISTER'
  | 'MODULE_FINANCIAL'
  | 'MODULE_CASH_ERRORS'
  | 'MODULE_AGENDA'
  | 'MODULE_MARKETING'
  | 'MODULE_DOWNLOADS'
  | 'MODULE_DOCUMENTS'
  | 'MODULE_ADMIN_USERS'
  | 'MODULE_ACCESS_CONTROL'
  | 'MODULE_AUDIT'
  | 'MODULE_SETTINGS';

export const PERMISSIONS_MAP: Record<PermissionKey, Role[]> = {
  MODULE_DASHBOARD: ['ADMIN', 'MANAGER'],
  MODULE_METAS: ['ADMIN'],
  MODULE_PURCHASES: ['ADMIN', 'MANAGER'],
  MODULE_COTAS: ['ADMIN', 'MANAGER'],
  MODULE_ICECREAM: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_CASH_REGISTER: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_FINANCIAL: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_CASH_ERRORS: ['ADMIN', 'CASHIER', 'MANAGER'], // Liberado Manager para ver histórico
  MODULE_AGENDA: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_MARKETING: ['ADMIN', 'MANAGER'],
  MODULE_DOWNLOADS: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_DOCUMENTS: ['ADMIN', 'MANAGER', 'CASHIER'],
  MODULE_ADMIN_USERS: ['ADMIN'],
  MODULE_ACCESS_CONTROL: ['ADMIN'],
  MODULE_AUDIT: ['ADMIN'],
  MODULE_SETTINGS: ['ADMIN']
};
